FROM node:alpine
COPY . /app
WORKDIR ./app
RUN npm install 
ENTRYPOINT ["/bin/sh"]
CMD ["entrypoint.sh"]
COPY entrypoint.sh /usr/local/bin/
RUN npm install && chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
